version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      RAILS_ENV: development
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
  db:
    image: postgres
    ports:
      - "5433:5432"
    env_file:
      - .env
    restart: always
    volumes:
      - ./shared/pg_data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  bundle:
  redis_data: