default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("POSTGRES_USER") { "onizuka" } %> 
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "potolok149" } %> 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: htsit_development
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>

test:
  <<: *default
  database: htsit_test
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
#
production:
  <<: *default
  database: htsit_production
